// import './globals.css'
// import { Inter } from 'next/font/google'
// import Navbar from '../app/navbar/navbar';
// import Footer from '../app/footer/footer';

// import { getServerSession } from "next-auth";
// import SessionProvider from "../../utils/SessionProvider";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const session = await getServerSession();
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <SessionProvider session={session}>
//           <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
//       <Navbar />
//         {children}
//         </div>
//         </SessionProvider>
//         <Footer />
//         </body>
//     </html>
//   )
// }

// import Navbar from "../app/navbar/navbar";
// import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

// import { getServerSession } from "next-auth";
// import SessionProvider from "../../utils/SessionProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = await getServerSession();
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider session={session}>
//           <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
//             <Navbar />
//             {children}
//           </div>
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }

import Navbar from "../app/navbar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "../../utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <AuthProvider>
           
           
            {children}
            </AuthProvider>
          
      </body>
    </html>
  );
}

